AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "SAM template for backend and related functions"

Metadata:
  Globals:
    Function:
      Tracing: Active
    Api:
      Cors: 
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        AllowHeaders: "'Accept-Encoding,Content-Encoding,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Client-ID,key,secret,session'"
        AllowOrigin: "'*'"

Resources:
  # define api gateway
  ApiGatewayBackend:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prd

  # define the Lambda function and its code
  CreateLayer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://easy-layers/functions/src/
      Handler: create_layer.lambda_handler
      Runtime: python3.9
      Description: Creates & Checks If A Layer Exists When Someone Submits
      Timeout: 300
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayBackend
            Path: /create_layer
            Method: post
      Layers:
        - arn:aws:lambda:us-east-1:737802338670:layer:jsonschema:1
        - arn:aws:lambda:us-east-1:737802338670:layer:requests-2-28-1:1
      Policies:
        Statement:
          - Effect: Allow
            Action: 
              - logs:CreateLogGroup
            Resource: arn:aws:logs:us-east-1:737802338670:*
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - arn:aws:logs:us-east-1:737802338670:log-group:/aws/lambda/create_update_python_layers:*
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - lambda:ListFunctions
              - lambda:ListLayerVersions
              - lambda:ListLayers
            Resource: "*"
          - Sid: VisualEditor1
            Effect: Allow
            Action:
              - lambda:GetLayerVersion
              - lambda:DeleteLayerVersion
              - lambda:AddLayerVersionPermission
            Resource: "*"
          - Sid: VisualEditor2
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObjectAcl
              - s3:GetObject
              - logs:CreateLogStream
              - lambda:PublishLayerVersion
              - s3:ListBucket
              - logs:PutLogEvents
            Resource:
              - "*"

  GetLayers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .src/
      Handler: get_layers.lambda_handler
      Runtime: python3.9
      Description: Creates & Checks If A Layer Exists When Someone Submits
      Timeout: 60
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayBackend
            Path: /create_layer
            Method: get 
            RequestParameters:
              - method.request.querystring.library:
                  Required: true
              - method.request.querystring.version:
                  Required: false
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - lambda:GetLayerVersion
                - lambda:ListLayerVersions
                - lambda:ListLayers
              Resource: "*"
            - Sid: VisualEditor1
              Effect: Allow
              Action:
                - s3:ListBucket
                - logs:CreateLogGroup
              Resource:
                - arn:aws:s3:::easy-layers
                - arn:aws:logs:us-east-1:737802338670:*
            - Sid: VisualEditor2
              Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:us-east-1:737802338670:log-group:/aws/lambda/easy_layers_get_layers:*